#!/usr/bin/env python3

'''
Copyright (c) 2015, Maxim Konakov
All rights reserved.

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice,
   this list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.
3. Neither the name of the copyright holder nor the names of its contributors
   may be used to endorse or promote products derived from this software without
   specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
'''

from sys import exit, argv, stderr, version_info

if version_info.major < 3 or (version_info.major == 3 and version_info.minor < 4):
	exit('ERROR: The script requires Python version 3.4.0 or newer')

from os import readlink, cpu_count
from pathlib import Path
from errno import ENOENT
from subprocess import Popen, PIPE
from hashlib import md5
from pickle import dump as store_data, load as load_data, PickleError
from collections import namedtuple

# helpers ---------------------------------------------------------------------------------------------
# error exit
def die(obj):
	exit('ERROR: ' + str(obj))

# external command invocation
def start_external(*args):
	return Popen(args, universal_newlines = True, stdout = PIPE, stderr = PIPE)

def get_external_result(proc):
	out, err = proc.communicate()

	if proc.poll() == 0:
		return out.strip()

	raise RuntimeError(err.strip())

# safe unlink
def safe_unlink(file):
	try:
		file.unlink()
	except OSError:
		pass

# pickle data in one transaction
def save_data(file, data):
	new_file = file.with_suffix('.new')

	try:
		with new_file.open('wb') as f:
			store_data(data, f, 4)	# '4' is the protocol version

		new_file.replace(file)
	except:
		safe_unlink(new_file)
		raise

# setup -----------------------------------------------------------------------------------------------
DIRT_HOME = Path('.dirt')
STATE_FILE = DIRT_HOME.joinpath('state')

# excluded pattern list
def get_excluded():
	try:
		with DIRT_HOME.joinpath('excluded').open() as f:
			return tuple(filter(None, (s.strip() for s in f)))
	except OSError as e:
		if e.errno == ENOENT:
			return ()
		die('Cannot read excluded globs: ' + str(e))

# directory check
def check_dir():
	if not DIRT_HOME.exists() or not DIRT_HOME.is_dir():
		die('This directory is not initialised.')

# number of CPU on this machine
NUM_CPU = cpu_count()

if NUM_CPU is None:
	NUM_CPU = 1

# data save/restore -----------------------------------------------------------------------------------
def save_state(data):
	try:
		save_data(STATE_FILE, data)
	except (PickleError, OSError) as e:
		die('Cannot store directory state data: ' + str(e))

def load_state():
	try:
		with STATE_FILE.open('rb') as f:
			return load_data(f)
	except PickleError as e:
		die('Directory state file is corrupt: ' + str(e))
	except OSError as e:
		if e.errno == ENOENT:
			return {}
		die('Cannot read directory state file: ' + str(e))

# directory reader ------------------------------------------------------------------------------------
def select_files():
	excluded = get_excluded()
	dirs = []

	def select(entry):
		if any(map(entry.match, excluded)):
			return False
		if entry.is_symlink() or entry.is_file():
			return True
		if entry.is_dir():
			dirs.append(entry)
		return False

	yield from filter(lambda entry: entry != DIRT_HOME and select(entry), Path().iterdir())

	while dirs:
		yield from filter(select, dirs.pop().iterdir())

# checksum calculations -------------------------------------------------------------------------------
def start_calc_file_sum(name):
	return start_external('md5sum', name)

def get_file_sum(proc):
	return int(get_external_result(proc).split(maxsplit = 1)[0], base = 16)

def int_sum(cs):
	return int.from_bytes(cs.digest(), 'big')

CHUNK_SIZE = 512 * 1024

def calc_file_sum(name):
	cs = md5()

	with open(name, 'rb', buffering = 0) as f:
		chunk = f.read(CHUNK_SIZE)

		while chunk:
			cs.update(chunk)
			chunk = f.read(CHUNK_SIZE)

	return int_sum(cs)
	#return get_file_sum(start_calc_file_sum(name))

def calc_short_sum(entry):
	with entry.open('rb') as f:
		return int_sum(md5(f.read(CHUNK_SIZE)))

# file info type
FileInfo = namedtuple('FileInfo', 'size, short_sum, full_sum')

def symlink_info(name):
	path = bytes(readlink(name), 'utf-8')
	cs = int_sum(md5(path))
	return FileInfo(len(path), cs, cs)

# directory scanners ----------------------------------------------------------------------------------
# directory scan with md5 sums
def full_scan():
	running = {}

	try:
		for entry in select_files():
			name = str(entry)

			if entry.is_symlink():
				yield (name, symlink_info(name))
			else:
				size = entry.stat().st_size
				short_sum = calc_short_sum(entry)

				if size <= CHUNK_SIZE:
					yield (name, FileInfo(size, short_sum, short_sum))
				elif len(running) == 2 * NUM_CPU - 1:
					yield (name, FileInfo(size, short_sum, calc_file_sum(name)))
				else:
					running[name] = (size, short_sum, start_calc_file_sum(name))

			# check for completed jobs
			completed = []

			for name, (size, short_sum, proc) in running.items():
				if proc.poll() is not None:
					yield (name, FileInfo(size, short_sum, get_file_sum(proc)))
					completed.append(name)

			# clear completed
			for name in completed:
				del running[name]

		# wait for the remaining jobs to complete
		while running:
			name, (size, short_sum, proc) = running.popitem()
			yield (name, FileInfo(size, short_sum, get_file_sum(proc)))
	except:
		for _, _, proc in running.values():
			if proc.poll() is None:
				proc.terminate()
				proc.wait()
		raise

# directory diff scan
def diff_scan():
	prev = load_state()
	running = {}

	try:
		for entry in select_files():
			name = str(entry)
			prev_info = prev.pop(name, None)

			if prev_info is None:
				yield ('+', name)
			else:
				if entry.is_symlink():
					if symlink_info(name) != prev_info:
						yield ('*', name)
				else:
					size = entry.stat().st_size

					if size != prev_info.size or calc_short_sum(entry) != prev_info.short_sum:
						yield ('*', name)
					elif size > CHUNK_SIZE:
						if len(running) == 2 * NUM_CPU - 1:
							if calc_file_sum(name) != prev_info.full_sum:
								yield ('*', name)
						else:
							running[name] = (prev_info.full_sum, start_calc_file_sum(name))

			# check for completed jobs
			completed = []

			for name, (prev_sum, proc) in running.items():
				if proc.poll() is not None:
					if get_file_sum(proc) != prev_sum:
						yield ('*', name)

					completed.append(name)

			# clear completed
			for name in completed:
				del running[name]

		# wait for the remaining jobs to complete
		while running:
			name, (prev_sum, proc) = running.popitem()

			if get_file_sum(proc) != prev_sum:
				yield ('*', name)
	except:
		for _, proc in running.values():
			if proc.poll() is None:
				proc.terminate()
				proc.wait()
		raise

	# deleted entries
	for name in prev.keys():
		yield ('-', name)


# command processors -----------------------------------------------------------------------------------
def cmd_init():
	if not DIRT_HOME.exists():
		DIRT_HOME.mkdir()
	elif DIRT_HOME.is_dir():
		print('This directory seems already initialised.', file = stderr)
	else:
		die('This directory cannot be initialised as it already contains something called "{}"' \
			.format(DIRT_HOME.name))

def cmd_show():
	check_dir()

	for sym, name in diff_scan():
		print(sym, name)

def cmd_accept():
	check_dir()
	save_state(dict(full_scan()))

def cmd_reset():
	check_dir()

	try:
		STATE_FILE.unlink()
	except OSError as e:
		if e.errno != ENOENT:
			raise e

USAGE = \
'''Usage: {} COMMAND
List added, deleted and modified files in the current directory.

The COMMAND argument must be one of the following:
  show     display all modifications made since the last 'accept'
  accept   accept all the changes
  init     initialise the current directory for tracking
  reset    delete tracking state
  help     display this help and exit'''.format(Path(argv[0]).name)

def cmd_usage():
	exit(USAGE)

# entry point ----------------------------------------------------------------------------------------
COMMANDS = { 'init' : cmd_init, \
			 'show' : cmd_show, \
			 'accept' : cmd_accept, \
			 'reset' : cmd_reset,	\
			 'help' : cmd_usage }

if len(argv) == 1:
	cmd_usage()

if len(argv) > 2:
	print('ERROR: Invalid command line parameters\n', file = stderr)
	cmd_usage()

if argv[1] not in COMMANDS:
	print('ERROR: Unknown command "{}"\n'.format(argv[1]), file = stderr)
	cmd_usage()

try:
	COMMANDS[argv[1]]()
except KeyboardInterrupt:
	die('Interrupted.')
except OSError as e:
	die(e)
